### ISSUE TITLE
Not an Opendtu Instance?

### ISSUE THREAD

**Issue by carpshark** [OpenDTU-App/opendtu-react-native#157]
It somehow doesn't work as intended 
![Screenshot_2024-08-21-12-46-33-876_xyz commanderred opendtuapp-edit](https://github.com/user-attachments/assets/d04892ed-7b83-4d77-99b4-9b5a2cde35c8)
![Screenshot_2024-08-21-12-46-10-148_com android chrome-edit](https://github.com/user-attachments/assets/7e0895d2-45ae-4dd4-a430-7a869bdc64ce)

Is there maybe a prerequisite I need to fulfil?

Latest Opendtu app. 

Regards.

**Comment by CommanderRedYT** [comment]
Hm weird.

You can find the check here: https://github.com/OpenDTU-App/opendtu-react-native/blob/develop/src%2Fapi%2Fopendtuapi.ts#L297

Maybe you can try checking it in your browser what the opendtu returns

**Comment by carpshark** [comment]
Thx for your response, this is, what I get: 

![Screenshot_2024-08-22-15-02-13-083_com android chrome-edit](https://github.com/user-attachments/assets/9099591e-8be7-4e27-b4fb-9c120f4c8f21)

Regards

**Comment by CommanderRedYT** [comment]
Interesting, this should work. This is very weird.

**Comment by carpshark** [comment]
Sure, im Happy to beta test it, thx for your efforts!

**Comment by CommanderRedYT** [comment]
created the ticket #158

**Comment by CommanderRedYT** [comment]
Hi, can you try the latest release? (v0.5.4)

**Comment by carpshark** [comment]
Yeah sure, as soon as it is released, I will, thx for your efforts! 



On 16 September 2024 23:16:21 CEST, Florian Wetzel ***@***.***> wrote:
>Hi, can you try the latest release? (v0.5.4)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenDTU-App/opendtu-react-native/issues/157#issuecomment-2354048653
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Phone.

**Comment by carpshark** [comment]
Hey, Not sure, where the logging is going to, but the result remains the same unfortunately 😕

**Comment by CommanderRedYT** [comment]
Okay, I did not realize that this button does not exist when no device was setup. After [this](https://github.com/OpenDTU-App/opendtu-react-native/pull/188) PR you should be able to visit the log screen in the setup screens.

**Comment by CommanderRedYT** [comment]
https://github.com/OpenDTU-App/opendtu-react-native/releases/tag/v0.5.5

**Comment by carpshark** [comment]
That did the trick, here's the log
[opendtu-app-logs.txt](https://github.com/user-attachments/files/17021168/opendtu-app-logs.txt)

**Comment by carpshark** [comment]
Let's close this issue, after upgrading my opendtu, it's now recognised by the app!

**Comment by carpshark** [comment]
Thx for the assistance!

**Comment by CommanderRedYT** [comment]
Glad to hear!
