### ISSUE TITLE
Influxdb

### ISSUE THREAD

**Issue by coltc50** [OpenDTU-App/opendtu-react-native#16]
I use influxdb. Is there a way to connect to influxdb database?

**Comment by CommanderRedYT** [comment]
Should be possible, although I would need some database to test it. Is the table in a lets say common format that is usable from multiple users? Like, can we somehow generalize it in a way (also with configuration) that multiple users can use it?

**Comment by CommanderRedYT** [comment]
No answer, closing this thread now.
