### ISSUE TITLE
Bug with inverters page

### ISSUE THREAD

**Issue by GaetanNaulin** [OpenDTU-App/opendtu-react-native#170]
Hi,
I don't know if it's normal or not, but I can't access to "Inverter" tab, at the bottom of the screen. The App automatically closes.
I'm on the 0.5.0, but I've 2 inverters on my DTU. On the Graphs page, my multiple inverters are correctly displayed.
Thanks.

**Comment by CommanderRedYT** [comment]
Hi, this is unexpected. What OpenDTU version do you have? I have multiple inverters and the app does not crash.

**Comment by GaetanNaulin** [comment]
I'm on the lastest : v24.8.5
My inverters are two HM-800-2T.
Can I have tracelog in the app ?

**Comment by CommanderRedYT** [comment]
Log-Viewer will be implemented soon (#166). However, this will not help here as it cannot log crashes.

You can use adb for this.

**Comment by CommanderRedYT** [comment]
Could you kindly also provide what the livestatus json endpoint returns?

**Comment by GaetanNaulin** [comment]
The return from the OpenDTU url : /api/system/status ?

**Comment by CommanderRedYT** [comment]
Yes, although maybe the status from inside the websocket could be different and cause the problem. If you can, it would be nice to have both! Thanks in advance

**Comment by GaetanNaulin** [comment]
Here the status of /api/system/status from my OpenDTU (I've removed the hostname) :

```
{"hostname":"","sdkversion":"v4.4.7-dirty","cpufreq":240,"cputemp":57.22222519,"heap_total":284504,"heap_used":129232,"heap_max_block":110580,"heap_min_free":86944,"psram_total":0,"psram_used":0,"sketch_total":1966080,"sketch_used":1673136,"littlefs_total":196608,"littlefs_used":24576,"chiprevision":3,"chipmodel":"ESP32-D0WD-V3","chipcores":2,"flashsize":4194304,"resetreason_0":"Software reset CPU","resetreason_1":"Software reset CPU","cfgsavecount":23,"config_version":"0.1.28","git_hash":"v24.8.5","pioenv":"generic_esp32","uptime":327029,"nrf_configured":true,"nrf_connected":true,"nrf_pvariant":true,"cmt_configured":false,"cmt_connected":false}
``` 

If you need another data, I can try to get it.

**Comment by CommanderRedYT** [comment]
Oh uhm sorry, I think thats the wrong endpoint. I meant `/api/livedata/status`

**Comment by GaetanNaulin** [comment]
No problem, here the result of /api/livedata/status (I've removed serial) :

```json
{
  "inverters":[
  {
    "serial":"",
    "name":"HM-800-SO-2",
    "order":1,
    "data_age":9920,
    "poll_enabled":true,
    "reachable":false,
    "producing":false,
    "limit_relative":100,
    "limit_absolute":800
  },
  {
    "serial":"",
    "name":"HM-800-SO-1",
    "order":0,
    "data_age":9945,
    "poll_enabled":true,
    "reachable":false,
    "producing":false,
    "limit_relative":100,
    "limit_absolute":800
  }
],
"total":{
  "Power":{
    "v":0,
    "u":"W",
    "d":1
  },
  "YieldDay":{
    "v":2290,
    "u":"Wh",
    "d":0
  },
  "YieldTotal":{
    "v":40.94499969,
    "u":"kWh",
    "d":3
  }
  },
  "hints":{
    "time_sync":false,
    "radio_problem":false,
    "default_password":false
  }
}
```

**Comment by CommanderRedYT** [comment]
Hi, I cannot reproduce this... It happens when you just switch to the inverters tab, right? Unfortunately, the stack trace from logcat sadly does not provide enough information about what happened. I tried injecting the state of your app into my development build, but I was not successful.

I am to be honest not sure how to continue, I can however give you these options:
- You can contact me via email and maybe we can find a way that I can connect to your instance.
- You could try and build the app yourself so you have proper crashdumps.

Sorry about this, but hopefully we can fix it! Fingers crossed!

**Comment by GaetanNaulin** [comment]
I will try to compile it, but I'm not familiar with react environment. What are the requirements to compile this project ? I installed yarn and react-native, but I'm not able to compilate at this time. (I'm on Ubuntu)

**Comment by CommanderRedYT** [comment]
I might have been able to find something with your stacktrace now, I will do another release later today. If this does not work / fix it, please try the following:

```bash
docker run --rm -it reactnativecommunity/react-native-android

# Inside the docker container
git clone https://github.com/OpenDTU-App/opendtu-react-native --recurse-submodules
cd opendtu-react-native
yarn
cd android
./gradlew assembleDebug
```

You can also try starting the dev-tools via `yarn start`, and if you already have the debug application on your phone it should allow you to connect via network.

**Comment by CommanderRedYT** [comment]
https://github.com/OpenDTU-App/opendtu-react-native/releases/tag/v0.5.3

**Comment by GaetanNaulin** [comment]
Yeah it's working ! Thanks !
