### ISSUE TITLE
wrong APK at v0.1.9 release?

### ISSUE THREAD

**Issue by IzzySoft** [OpenDTU-App/opendtu-react-native#20]
The arm64-v8a APK at [v0.1.9](https://github.com/OpenDTU-App/opendtu-react-native/releases/tag/v0.1.9) identifies as

    package: name='xyz.commanderred.opendtuapp' versionCode='6' versionName='0.1.8'

Expected would be a `versionName='0.1.9'`. Was the wrong APK attached accidentally – or just the versioning not adjusted before creating the release? [`build.gradle`](https://github.com/OpenDTU-App/opendtu-react-native/blob/develop/android/app/build.gradle#L83) makes me assume the latter:

```gradle
    defaultConfig {
        applicationId "xyz.commanderred.opendtuapp"
        setProperty("archivesBaseName", "OpenDTUApp")
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 6
        versionName "0.1.8"
    }
```

**Comment by CommanderRedYT** [comment]
Yes, I noticed this. I made the release manually instead of using a tool that would auto-increment all Version numbers. It's already merged to develop if I recall correctly, but I haven't made a release yet. (#19)

**Comment by IzzySoft** [comment]
Ah, so it's just the versioning, OK. I have [added your app](https://apt.izzysoft.de/packages/xyz.commanderred.opendtuapp/) to [my repo](https://apt.izzysoft.de/fdroid) yesterday. Its updater will check daily for new releases and pull them if available, so you now already have an update notifier for those using my repo via the [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) of their choice. But yeah, if `versionCode` was not increased, there won't be an update notification this way either…

Btw: you might consider making the in-app update notifier opt-in to avoid duplicated notifications, given this background :wink:

**Comment by CommanderRedYT** [comment]
Oh, thanks for doing this! Might make sense to make it opt-in, but let the default (if possible) be dependent on how the app was installed (through github or through other sources, if not possible, default should be off

**Comment by IzzySoft** [comment]
Can easily be left to those using the app I guess:

* have a setting for that which is boolean (on/off), initialized as `NULL`
* when the app is started and the value is `NULL`, open a pop-up asking what should be used
* if someone wants to re-decide later, have a settings entry for them to toggle

That way you don't have to track the install source (can get tedy, there are several [F-Droid clients](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) available and maybe more pop up in the future) – while the approach just outlined should be easy to maintain.

**Comment by CommanderRedYT** [comment]
You are totally right, thanks for the suggestion! Will probably implement it later today

**Comment by tm-107** [comment]
Same problem with 0.1.10-1?

**Comment by CommanderRedYT** [comment]
Seems like I forgot something again. This should not happen, I am sorry. I will fix things later. https://github.com/OpenDTU-App/opendtu-react-native/issues/25
