### ISSUE TITLE
CleartextTraffic

### ISSUE THREAD

**Issue by IzzySoft** [OpenDTU-App/opendtu-react-native#27]
My scanner got a few additional checks and reported on today's release:

    ! repo/xyz.commanderred.opendtuapp_7.apk declares flag(s): usesCleartextTraffic

I'm not familiar with the inverters and how they are communicated with, so could you please clarify what cleartext traffic is needed by the app? Thanks in advance!

**Comment by CommanderRedYT** [comment]
The communication doesn't happen to the inverter. It is going to a ESP-32 with a NRF24 module connected to it to speak a vendor specific protocol. The esp-32 does not have SSL, so for people who do not reverse-proxy it, communication using bare IP/http has to be possible

**Comment by IzzySoft** [comment]
Ah, my bad – of course the ESP. Now it makes totally sense, thanks!

![image](https://github.com/OpenDTU-App/opendtu-react-native/assets/6781438/0dcf6612-9bb5-4a18-89c0-a3b412ca8fb6)

**Comment by IzzySoft** [comment]
@CommanderRedYT could you please also clarify `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE`, which have recently been added? Thanks in advance!

**Comment by CommanderRedYT** [comment]
It is required for handling OTA updates. Unfortunately, right now react-native has some bugs that I can't handle it in-memory, so I am saving the binary file to the [temp directory](https://github.com/search?q=repo%3Aitinance%2Freact-native-fs+TemporaryDirectoryPath&type=code) and then uploading it from there.

**Comment by IzzySoft** [comment]
Thanks! Updated that accordingly here.
